### ISSUE TITLE
希望能提供html分支

### ISSUE THREAD

**Issue by iseeyo** [CodeIgniter-Chinese/codeigniter-user-guide#2]
很多widows用户或者初学者对Sphinx、Python一窍不通，即便安装了也不知道怎么编译成文档，希望能提供一份编译完成的html，代表所有正在学习的同学们感谢您！

**Comment by iseeyo** [comment]
非常感谢

pinnetcn@qq.com

发件人： Hex
发送时间： 2015-08-27 18:57
收件人： CodeIgniter-Chinese/codeigniter-user-guide
抄送： iseeyo
主题： Re: [codeigniter-user-guide] 希望能提供html分支 (#2)
已经提供了 HTML 分支，并且可以下载 HTML 压缩包 http://codeigniter-chinese.github.io/codeigniter-user-guide/index.html 这里底部有下载链接。

**Comment by Tengfei1010** [comment]
:+1:
